version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"

  auth:
    build: ./auth
    ports:
      - "3001:3001"

  students:
    build: ./students
    ports:
      - "3002:3002"

  professors:
    build: ./professors
    ports:
      - "3003:3003"
